// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cex

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	decimal "github.com/shopspring/decimal"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson12993614DecodeGithubComShaovieCex(in *jlexer.Lexer, out *BigoneSpotWsPubMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "error":
			easyjson12993614Decode(in, &out.Err)
		case "depthSnapshot":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.DepthSnap).UnmarshalJSON(data))
				}
			}
		case "depthUpdate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.DepthUpdate).UnmarshalJSON(data))
				}
			}
		case "tickersSnapshot":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.TickerSnap).UnmarshalJSON(data))
				}
			}
		case "tickerUpdate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.TickerUpdate).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12993614EncodeGithubComShaovieCex(out *jwriter.Writer, in BigoneSpotWsPubMsg) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"error\":"
		first = false
		out.RawString(prefix[1:])
		easyjson12993614Encode(out, in.Err)
	}
	if len(in.DepthSnap) != 0 {
		const prefix string = ",\"depthSnapshot\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.DepthSnap).MarshalJSON())
	}
	if len(in.DepthUpdate) != 0 {
		const prefix string = ",\"depthUpdate\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.DepthUpdate).MarshalJSON())
	}
	if len(in.TickerSnap) != 0 {
		const prefix string = ",\"tickersSnapshot\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.TickerSnap).MarshalJSON())
	}
	if len(in.TickerUpdate) != 0 {
		const prefix string = ",\"tickerUpdate\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.TickerUpdate).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BigoneSpotWsPubMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson12993614EncodeGithubComShaovieCex(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BigoneSpotWsPubMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson12993614EncodeGithubComShaovieCex(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BigoneSpotWsPubMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson12993614DecodeGithubComShaovieCex(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BigoneSpotWsPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson12993614DecodeGithubComShaovieCex(l, v)
}
func easyjson12993614Decode(in *jlexer.Lexer, out *struct {
	Code int    `json:"code,omitempty"`
	Msg  string `json:"message,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = int(in.Int())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Msg = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12993614Encode(out *jwriter.Writer, in struct {
	Code int    `json:"code,omitempty"`
	Msg  string `json:"message,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Code != 0 {
		const prefix string = ",\"code\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	if in.Msg != "" {
		const prefix string = ",\"message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Msg))
	}
	out.RawByte('}')
}
func easyjson12993614DecodeGithubComShaovieCex1(in *jlexer.Lexer, out *BigoneSpotWsPrivMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "error":
			easyjson12993614Decode(in, &out.Err)
		case "orderUpdate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.OrderUpdate).UnmarshalJSON(data))
				}
			}
		case "accountsSnapshot":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.AccountSnap).UnmarshalJSON(data))
				}
			}
		case "accountUpdate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.AccountUpdate).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12993614EncodeGithubComShaovieCex1(out *jwriter.Writer, in BigoneSpotWsPrivMsg) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"error\":"
		first = false
		out.RawString(prefix[1:])
		easyjson12993614Encode(out, in.Err)
	}
	if len(in.OrderUpdate) != 0 {
		const prefix string = ",\"orderUpdate\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.OrderUpdate).MarshalJSON())
	}
	if len(in.AccountSnap) != 0 {
		const prefix string = ",\"accountsSnapshot\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.AccountSnap).MarshalJSON())
	}
	if len(in.AccountUpdate) != 0 {
		const prefix string = ",\"accountUpdate\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.AccountUpdate).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BigoneSpotWsPrivMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson12993614EncodeGithubComShaovieCex1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BigoneSpotWsPrivMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson12993614EncodeGithubComShaovieCex1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BigoneSpotWsPrivMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson12993614DecodeGithubComShaovieCex1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BigoneSpotWsPrivMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson12993614DecodeGithubComShaovieCex1(l, v)
}
func easyjson12993614DecodeGithubComShaovieCex2(in *jlexer.Lexer, out *BigoneSpotOrderBookItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Price).UnmarshalJSON(data))
				}
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Qty = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12993614EncodeGithubComShaovieCex2(out *jwriter.Writer, in BigoneSpotOrderBookItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix[1:])
		out.Raw((in.Price).MarshalJSON())
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Qty))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BigoneSpotOrderBookItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson12993614EncodeGithubComShaovieCex2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BigoneSpotOrderBookItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson12993614EncodeGithubComShaovieCex2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BigoneSpotOrderBookItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson12993614DecodeGithubComShaovieCex2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BigoneSpotOrderBookItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson12993614DecodeGithubComShaovieCex2(l, v)
}
func easyjson12993614DecodeGithubComShaovieCex3(in *jlexer.Lexer, out *BigoneSpotOrderBookDepth) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "market":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "bids":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([]BigoneSpotOrderBookItem, 0, 2)
					} else {
						out.Bids = []BigoneSpotOrderBookItem{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v1 BigoneSpotOrderBookItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Bids = append(out.Bids, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "asks":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([]BigoneSpotOrderBookItem, 0, 2)
					} else {
						out.Asks = []BigoneSpotOrderBookItem{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v2 BigoneSpotOrderBookItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.Asks = append(out.Asks, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12993614EncodeGithubComShaovieCex3(out *jwriter.Writer, in BigoneSpotOrderBookDepth) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"market\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"bids\":"
		out.RawString(prefix)
		if in.Bids == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Bids {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"asks\":"
		out.RawString(prefix)
		if in.Asks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Asks {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BigoneSpotOrderBookDepth) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson12993614EncodeGithubComShaovieCex3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BigoneSpotOrderBookDepth) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson12993614EncodeGithubComShaovieCex3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BigoneSpotOrderBookDepth) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson12993614DecodeGithubComShaovieCex3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BigoneSpotOrderBookDepth) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson12993614DecodeGithubComShaovieCex3(l, v)
}
func easyjson12993614DecodeGithubComShaovieCex4(in *jlexer.Lexer, out *BigoneSpotOrderBook) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "depth":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Depth).UnmarshalEasyJSON(in)
			}
		case "changeId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChangeId = string(in.String())
			}
		case "prevId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12993614EncodeGithubComShaovieCex4(out *jwriter.Writer, in BigoneSpotOrderBook) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"depth\":"
		first = false
		out.RawString(prefix[1:])
		(in.Depth).MarshalEasyJSON(out)
	}
	if in.ChangeId != "" {
		const prefix string = ",\"changeId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ChangeId))
	}
	if in.PrevId != "" {
		const prefix string = ",\"prevId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PrevId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BigoneSpotOrderBook) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson12993614EncodeGithubComShaovieCex4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BigoneSpotOrderBook) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson12993614EncodeGithubComShaovieCex4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BigoneSpotOrderBook) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson12993614DecodeGithubComShaovieCex4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BigoneSpotOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson12993614DecodeGithubComShaovieCex4(l, v)
}
func easyjson12993614DecodeGithubComShaovieCex5(in *jlexer.Lexer, out *BigoneSpot24hTicker) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = int(in.Int())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Msg = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]struct {
							Symbol string `json:"asset_pair_name"`
							Bid    struct {
								Price decimal.Decimal `json:"price"`
							} `json:"bid"`
							Ask struct {
								Price decimal.Decimal `json:"price"`
							} `json:"ask"`
							Volume      decimal.Decimal `json:"base_volume"`
							QuoteVolume decimal.Decimal `json:"quote_volume"`
						}, 0, 0)
					} else {
						out.Data = []struct {
							Symbol string `json:"asset_pair_name"`
							Bid    struct {
								Price decimal.Decimal `json:"price"`
							} `json:"bid"`
							Ask struct {
								Price decimal.Decimal `json:"price"`
							} `json:"ask"`
							Volume      decimal.Decimal `json:"base_volume"`
							QuoteVolume decimal.Decimal `json:"quote_volume"`
						}{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v7 struct {
						Symbol string `json:"asset_pair_name"`
						Bid    struct {
							Price decimal.Decimal `json:"price"`
						} `json:"bid"`
						Ask struct {
							Price decimal.Decimal `json:"price"`
						} `json:"ask"`
						Volume      decimal.Decimal `json:"base_volume"`
						QuoteVolume decimal.Decimal `json:"quote_volume"`
					}
					easyjson12993614Decode1(in, &v7)
					out.Data = append(out.Data, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12993614EncodeGithubComShaovieCex5(out *jwriter.Writer, in BigoneSpot24hTicker) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Code != 0 {
		const prefix string = ",\"code\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	if in.Msg != "" {
		const prefix string = ",\"message\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Msg))
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v8, v9 := range in.Data {
				if v8 > 0 {
					out.RawByte(',')
				}
				easyjson12993614Encode1(out, v9)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BigoneSpot24hTicker) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson12993614EncodeGithubComShaovieCex5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BigoneSpot24hTicker) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson12993614EncodeGithubComShaovieCex5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BigoneSpot24hTicker) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson12993614DecodeGithubComShaovieCex5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BigoneSpot24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson12993614DecodeGithubComShaovieCex5(l, v)
}
func easyjson12993614Decode1(in *jlexer.Lexer, out *struct {
	Symbol string `json:"asset_pair_name"`
	Bid    struct {
		Price decimal.Decimal `json:"price"`
	} `json:"bid"`
	Ask struct {
		Price decimal.Decimal `json:"price"`
	} `json:"ask"`
	Volume      decimal.Decimal `json:"base_volume"`
	QuoteVolume decimal.Decimal `json:"quote_volume"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "asset_pair_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "bid":
			easyjson12993614Decode2(in, &out.Bid)
		case "ask":
			easyjson12993614Decode2(in, &out.Ask)
		case "base_volume":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Volume).UnmarshalJSON(data))
				}
			}
		case "quote_volume":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.QuoteVolume).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12993614Encode1(out *jwriter.Writer, in struct {
	Symbol string `json:"asset_pair_name"`
	Bid    struct {
		Price decimal.Decimal `json:"price"`
	} `json:"bid"`
	Ask struct {
		Price decimal.Decimal `json:"price"`
	} `json:"ask"`
	Volume      decimal.Decimal `json:"base_volume"`
	QuoteVolume decimal.Decimal `json:"quote_volume"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"asset_pair_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"bid\":"
		out.RawString(prefix)
		easyjson12993614Encode2(out, in.Bid)
	}
	{
		const prefix string = ",\"ask\":"
		out.RawString(prefix)
		easyjson12993614Encode2(out, in.Ask)
	}
	{
		const prefix string = ",\"base_volume\":"
		out.RawString(prefix)
		out.Raw((in.Volume).MarshalJSON())
	}
	{
		const prefix string = ",\"quote_volume\":"
		out.RawString(prefix)
		out.Raw((in.QuoteVolume).MarshalJSON())
	}
	out.RawByte('}')
}
func easyjson12993614Decode2(in *jlexer.Lexer, out *struct {
	Price decimal.Decimal `json:"price"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Price).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson12993614Encode2(out *jwriter.Writer, in struct {
	Price decimal.Decimal `json:"price"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix[1:])
		out.Raw((in.Price).MarshalJSON())
	}
	out.RawByte('}')
}
