// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package cex

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (BigoneSpot24hTicker) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BigoneSpot24hTicker) UnmarshalJSON([]byte) error        { return nil }
func (BigoneSpot24hTicker) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BigoneSpot24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BigoneSpot24hTicker *BigoneSpot24hTicker

func (BigoneSpotOrderBook) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BigoneSpotOrderBook) UnmarshalJSON([]byte) error        { return nil }
func (BigoneSpotOrderBook) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BigoneSpotOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BigoneSpotOrderBook *BigoneSpotOrderBook

func (BigoneSpotOrderBookDepth) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BigoneSpotOrderBookDepth) UnmarshalJSON([]byte) error        { return nil }
func (BigoneSpotOrderBookDepth) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BigoneSpotOrderBookDepth) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BigoneSpotOrderBookDepth *BigoneSpotOrderBookDepth

func (BigoneSpotOrderBookItem) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BigoneSpotOrderBookItem) UnmarshalJSON([]byte) error        { return nil }
func (BigoneSpotOrderBookItem) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BigoneSpotOrderBookItem) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BigoneSpotOrderBookItem *BigoneSpotOrderBookItem

func (BigoneSpotWsPrivMsg) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BigoneSpotWsPrivMsg) UnmarshalJSON([]byte) error        { return nil }
func (BigoneSpotWsPrivMsg) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BigoneSpotWsPrivMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BigoneSpotWsPrivMsg *BigoneSpotWsPrivMsg

func (BigoneSpotWsPubMsg) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BigoneSpotWsPubMsg) UnmarshalJSON([]byte) error        { return nil }
func (BigoneSpotWsPubMsg) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BigoneSpotWsPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BigoneSpotWsPubMsg *BigoneSpotWsPubMsg
