// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package cex

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (BinanceFutures24hTicker) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceFutures24hTicker) UnmarshalJSON([]byte) error        { return nil }
func (BinanceFutures24hTicker) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceFutures24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceFutures24hTicker *BinanceFutures24hTicker

func (BinanceFuturesBBO) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceFuturesBBO) UnmarshalJSON([]byte) error        { return nil }
func (BinanceFuturesBBO) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceFuturesBBO) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceFuturesBBO *BinanceFuturesBBO

func (BinanceFuturesOrderBook) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceFuturesOrderBook) UnmarshalJSON([]byte) error        { return nil }
func (BinanceFuturesOrderBook) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceFuturesOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceFuturesOrderBook *BinanceFuturesOrderBook

func (BinanceSpot24hTicker) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceSpot24hTicker) UnmarshalJSON([]byte) error        { return nil }
func (BinanceSpot24hTicker) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceSpot24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceSpot24hTicker *BinanceSpot24hTicker

func (BinanceSpotBBO) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceSpotBBO) UnmarshalJSON([]byte) error        { return nil }
func (BinanceSpotBBO) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceSpotBBO) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceSpotBBO *BinanceSpotBBO

func (BinanceSpotOrderBook) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceSpotOrderBook) UnmarshalJSON([]byte) error        { return nil }
func (BinanceSpotOrderBook) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceSpotOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceSpotOrderBook *BinanceSpotOrderBook

func (BinanceWsPubMsg) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceWsPubMsg) UnmarshalJSON([]byte) error        { return nil }
func (BinanceWsPubMsg) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceWsPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceWsPubMsg *BinanceWsPubMsg
