// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cex

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	decimal "github.com/shopspring/decimal"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC5a5ed42DecodeGithubComShaovieCex(in *jlexer.Lexer, out *BinanceWsPubMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = int(in.Int())
			}
		case "stream":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Stream = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Data).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a5ed42EncodeGithubComShaovieCex(out *jwriter.Writer, in BinanceWsPubMsg) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Code != 0 {
		const prefix string = ",\"code\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	if in.Stream != "" {
		const prefix string = ",\"stream\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Stream))
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Data).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BinanceWsPubMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5a5ed42EncodeGithubComShaovieCex(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BinanceWsPubMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a5ed42EncodeGithubComShaovieCex(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BinanceWsPubMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5a5ed42DecodeGithubComShaovieCex(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BinanceWsPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a5ed42DecodeGithubComShaovieCex(l, v)
}
func easyjsonC5a5ed42DecodeGithubComShaovieCex1(in *jlexer.Lexer, out *BinanceSpotOrderBook) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bids":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Bids = [][2]decimal.Decimal{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v1 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v2 := 0
						for !in.IsDelim(']') {
							if v2 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v1)[v2]).UnmarshalJSON(data))
									}
								}
								v2++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Bids = append(out.Bids, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "asks":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Asks = [][2]decimal.Decimal{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v3 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v4 := 0
						for !in.IsDelim(']') {
							if v4 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v3)[v4]).UnmarshalJSON(data))
									}
								}
								v4++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Asks = append(out.Asks, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a5ed42EncodeGithubComShaovieCex1(out *jwriter.Writer, in BinanceSpotOrderBook) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Bids) != 0 {
		const prefix string = ",\"bids\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v5, v6 := range in.Bids {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v7 := range v6 {
					if v7 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v6)[v7]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	if len(in.Asks) != 0 {
		const prefix string = ",\"asks\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v8, v9 := range in.Asks {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v10 := range v9 {
					if v10 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v9)[v10]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BinanceSpotOrderBook) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5a5ed42EncodeGithubComShaovieCex1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BinanceSpotOrderBook) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a5ed42EncodeGithubComShaovieCex1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BinanceSpotOrderBook) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5a5ed42DecodeGithubComShaovieCex1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BinanceSpotOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a5ed42DecodeGithubComShaovieCex1(l, v)
}
func easyjsonC5a5ed42DecodeGithubComShaovieCex2(in *jlexer.Lexer, out *BinanceSpotBBO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "b":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BidPrice).UnmarshalJSON(data))
				}
			}
		case "B":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BidQty).UnmarshalJSON(data))
				}
			}
		case "a":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.AskPrice).UnmarshalJSON(data))
				}
			}
		case "A":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.AskQty).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a5ed42EncodeGithubComShaovieCex2(out *jwriter.Writer, in BinanceSpotBBO) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Symbol != "" {
		const prefix string = ",\"s\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	if true {
		const prefix string = ",\"b\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.BidPrice).MarshalJSON())
	}
	if true {
		const prefix string = ",\"B\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.BidQty).MarshalJSON())
	}
	if true {
		const prefix string = ",\"a\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.AskPrice).MarshalJSON())
	}
	if true {
		const prefix string = ",\"A\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.AskQty).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BinanceSpotBBO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5a5ed42EncodeGithubComShaovieCex2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BinanceSpotBBO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a5ed42EncodeGithubComShaovieCex2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BinanceSpotBBO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5a5ed42DecodeGithubComShaovieCex2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BinanceSpotBBO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a5ed42DecodeGithubComShaovieCex2(l, v)
}
func easyjsonC5a5ed42DecodeGithubComShaovieCex3(in *jlexer.Lexer, out *BinanceSpot24hTicker) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "c":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Last).UnmarshalJSON(data))
				}
			}
		case "v":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Volume).UnmarshalJSON(data))
				}
			}
		case "q":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.QuoteVolume).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a5ed42EncodeGithubComShaovieCex3(out *jwriter.Writer, in BinanceSpot24hTicker) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"c\":"
		out.RawString(prefix)
		out.Raw((in.Last).MarshalJSON())
	}
	{
		const prefix string = ",\"v\":"
		out.RawString(prefix)
		out.Raw((in.Volume).MarshalJSON())
	}
	{
		const prefix string = ",\"q\":"
		out.RawString(prefix)
		out.Raw((in.QuoteVolume).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BinanceSpot24hTicker) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5a5ed42EncodeGithubComShaovieCex3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BinanceSpot24hTicker) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a5ed42EncodeGithubComShaovieCex3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BinanceSpot24hTicker) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5a5ed42DecodeGithubComShaovieCex3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BinanceSpot24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a5ed42DecodeGithubComShaovieCex3(l, v)
}
func easyjsonC5a5ed42DecodeGithubComShaovieCex4(in *jlexer.Lexer, out *BinanceFuturesOrderBook) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "e":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Event = string(in.String())
			}
		case "E":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "b":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Bids = [][2]decimal.Decimal{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v11 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v12 := 0
						for !in.IsDelim(']') {
							if v12 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v11)[v12]).UnmarshalJSON(data))
									}
								}
								v12++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Bids = append(out.Bids, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "a":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Asks = [][2]decimal.Decimal{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v13 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v14 := 0
						for !in.IsDelim(']') {
							if v14 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v13)[v14]).UnmarshalJSON(data))
									}
								}
								v14++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Asks = append(out.Asks, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a5ed42EncodeGithubComShaovieCex4(out *jwriter.Writer, in BinanceFuturesOrderBook) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Event != "" {
		const prefix string = ",\"e\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Event))
	}
	if in.Time != 0 {
		const prefix string = ",\"E\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Time))
	}
	if in.Symbol != "" {
		const prefix string = ",\"s\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Symbol))
	}
	if len(in.Bids) != 0 {
		const prefix string = ",\"b\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v15, v16 := range in.Bids {
				if v15 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v17 := range v16 {
					if v17 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v16)[v17]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	if len(in.Asks) != 0 {
		const prefix string = ",\"a\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v18, v19 := range in.Asks {
				if v18 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v20 := range v19 {
					if v20 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v19)[v20]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BinanceFuturesOrderBook) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5a5ed42EncodeGithubComShaovieCex4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BinanceFuturesOrderBook) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a5ed42EncodeGithubComShaovieCex4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BinanceFuturesOrderBook) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5a5ed42DecodeGithubComShaovieCex4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BinanceFuturesOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a5ed42DecodeGithubComShaovieCex4(l, v)
}
func easyjsonC5a5ed42DecodeGithubComShaovieCex5(in *jlexer.Lexer, out *BinanceFuturesBBO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "T":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "b":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BidPrice).UnmarshalJSON(data))
				}
			}
		case "B":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BidQty).UnmarshalJSON(data))
				}
			}
		case "a":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.AskPrice).UnmarshalJSON(data))
				}
			}
		case "A":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.AskQty).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a5ed42EncodeGithubComShaovieCex5(out *jwriter.Writer, in BinanceFuturesBBO) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Symbol != "" {
		const prefix string = ",\"s\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	if in.Time != 0 {
		const prefix string = ",\"T\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Time))
	}
	if true {
		const prefix string = ",\"b\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.BidPrice).MarshalJSON())
	}
	if true {
		const prefix string = ",\"B\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.BidQty).MarshalJSON())
	}
	if true {
		const prefix string = ",\"a\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.AskPrice).MarshalJSON())
	}
	if true {
		const prefix string = ",\"A\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.AskQty).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BinanceFuturesBBO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5a5ed42EncodeGithubComShaovieCex5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BinanceFuturesBBO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a5ed42EncodeGithubComShaovieCex5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BinanceFuturesBBO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5a5ed42DecodeGithubComShaovieCex5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BinanceFuturesBBO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a5ed42DecodeGithubComShaovieCex5(l, v)
}
func easyjsonC5a5ed42DecodeGithubComShaovieCex6(in *jlexer.Lexer, out *BinanceFutures24hTicker) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "c":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Last).UnmarshalJSON(data))
				}
			}
		case "v":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Volume).UnmarshalJSON(data))
				}
			}
		case "q":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.QuoteVolume).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a5ed42EncodeGithubComShaovieCex6(out *jwriter.Writer, in BinanceFutures24hTicker) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"c\":"
		out.RawString(prefix)
		out.Raw((in.Last).MarshalJSON())
	}
	{
		const prefix string = ",\"v\":"
		out.RawString(prefix)
		out.Raw((in.Volume).MarshalJSON())
	}
	{
		const prefix string = ",\"q\":"
		out.RawString(prefix)
		out.Raw((in.QuoteVolume).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BinanceFutures24hTicker) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5a5ed42EncodeGithubComShaovieCex6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BinanceFutures24hTicker) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a5ed42EncodeGithubComShaovieCex6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BinanceFutures24hTicker) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5a5ed42DecodeGithubComShaovieCex6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BinanceFutures24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a5ed42DecodeGithubComShaovieCex6(l, v)
}
