// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package cex

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (BinanceContractOrderBook) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceContractOrderBook) UnmarshalJSON([]byte) error        { return nil }
func (BinanceContractOrderBook) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceContractOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceContractOrderBook *BinanceContractOrderBook

func (BinanceSpot24hTicker) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceSpot24hTicker) UnmarshalJSON([]byte) error        { return nil }
func (BinanceSpot24hTicker) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceSpot24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceSpot24hTicker *BinanceSpot24hTicker

func (BinanceSpotOrderBook) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceSpotOrderBook) UnmarshalJSON([]byte) error        { return nil }
func (BinanceSpotOrderBook) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceSpotOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceSpotOrderBook *BinanceSpotOrderBook

func (BinanceWsContractPubMsg) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceWsContractPubMsg) UnmarshalJSON([]byte) error        { return nil }
func (BinanceWsContractPubMsg) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceWsContractPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceWsContractPubMsg *BinanceWsContractPubMsg

func (BinanceWsSpotPubMsg) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BinanceWsSpotPubMsg) UnmarshalJSON([]byte) error        { return nil }
func (BinanceWsSpotPubMsg) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BinanceWsSpotPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BinanceWsSpotPubMsg *BinanceWsSpotPubMsg
