// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cex

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	decimal "github.com/shopspring/decimal"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA6afe24DecodeGithubComShaovieCex(in *jlexer.Lexer, out *BybitWsPubMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ts":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "op":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Op = string(in.String())
			}
		case "topic":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Topic = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Data).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA6afe24EncodeGithubComShaovieCex(out *jwriter.Writer, in BybitWsPubMsg) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Time != 0 {
		const prefix string = ",\"ts\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.Time))
	}
	if in.Op != "" {
		const prefix string = ",\"op\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Op))
	}
	if in.Topic != "" {
		const prefix string = ",\"topic\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Topic))
	}
	if in.Type != "" {
		const prefix string = ",\"type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Type))
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Data).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BybitWsPubMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA6afe24EncodeGithubComShaovieCex(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BybitWsPubMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA6afe24EncodeGithubComShaovieCex(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BybitWsPubMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA6afe24DecodeGithubComShaovieCex(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BybitWsPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA6afe24DecodeGithubComShaovieCex(l, v)
}
func easyjsonA6afe24DecodeGithubComShaovieCex1(in *jlexer.Lexer, out *BybitSpotBBO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "b":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Bids = [][2]decimal.Decimal{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v1 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v2 := 0
						for !in.IsDelim(']') {
							if v2 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v1)[v2]).UnmarshalJSON(data))
									}
								}
								v2++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Bids = append(out.Bids, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "a":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Asks = [][2]decimal.Decimal{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v3 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v4 := 0
						for !in.IsDelim(']') {
							if v4 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v3)[v4]).UnmarshalJSON(data))
									}
								}
								v4++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Asks = append(out.Asks, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA6afe24EncodeGithubComShaovieCex1(out *jwriter.Writer, in BybitSpotBBO) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Symbol != "" {
		const prefix string = ",\"s\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	if len(in.Bids) != 0 {
		const prefix string = ",\"b\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v5, v6 := range in.Bids {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v7 := range v6 {
					if v7 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v6)[v7]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	if len(in.Asks) != 0 {
		const prefix string = ",\"a\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v8, v9 := range in.Asks {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v10 := range v9 {
					if v10 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v9)[v10]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BybitSpotBBO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA6afe24EncodeGithubComShaovieCex1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BybitSpotBBO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA6afe24EncodeGithubComShaovieCex1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BybitSpotBBO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA6afe24DecodeGithubComShaovieCex1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BybitSpotBBO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA6afe24DecodeGithubComShaovieCex1(l, v)
}
func easyjsonA6afe24DecodeGithubComShaovieCex2(in *jlexer.Lexer, out *BybitSpot24hTicker) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "c":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Last).UnmarshalJSON(data))
				}
			}
		case "v":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Volume).UnmarshalJSON(data))
				}
			}
		case "q":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.QuoteVolume).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA6afe24EncodeGithubComShaovieCex2(out *jwriter.Writer, in BybitSpot24hTicker) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"c\":"
		out.RawString(prefix)
		out.Raw((in.Last).MarshalJSON())
	}
	{
		const prefix string = ",\"v\":"
		out.RawString(prefix)
		out.Raw((in.Volume).MarshalJSON())
	}
	{
		const prefix string = ",\"q\":"
		out.RawString(prefix)
		out.Raw((in.QuoteVolume).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BybitSpot24hTicker) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA6afe24EncodeGithubComShaovieCex2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BybitSpot24hTicker) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA6afe24EncodeGithubComShaovieCex2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BybitSpot24hTicker) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA6afe24DecodeGithubComShaovieCex2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BybitSpot24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA6afe24DecodeGithubComShaovieCex2(l, v)
}
func easyjsonA6afe24DecodeGithubComShaovieCex3(in *jlexer.Lexer, out *BybitOrderBook) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "b":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Bids = [][2]decimal.Decimal{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v11 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v12 := 0
						for !in.IsDelim(']') {
							if v12 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v11)[v12]).UnmarshalJSON(data))
									}
								}
								v12++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Bids = append(out.Bids, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "a":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Asks = [][2]decimal.Decimal{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v13 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v14 := 0
						for !in.IsDelim(']') {
							if v14 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v13)[v14]).UnmarshalJSON(data))
									}
								}
								v14++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Asks = append(out.Asks, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA6afe24EncodeGithubComShaovieCex3(out *jwriter.Writer, in BybitOrderBook) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Symbol != "" {
		const prefix string = ",\"s\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	if len(in.Bids) != 0 {
		const prefix string = ",\"b\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v15, v16 := range in.Bids {
				if v15 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v17 := range v16 {
					if v17 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v16)[v17]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	if len(in.Asks) != 0 {
		const prefix string = ",\"a\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v18, v19 := range in.Asks {
				if v18 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v20 := range v19 {
					if v20 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v19)[v20]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BybitOrderBook) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA6afe24EncodeGithubComShaovieCex3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BybitOrderBook) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA6afe24EncodeGithubComShaovieCex3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BybitOrderBook) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA6afe24DecodeGithubComShaovieCex3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BybitOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA6afe24DecodeGithubComShaovieCex3(l, v)
}
