// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cex

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	decimal "github.com/shopspring/decimal"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC89930e1DecodeGithubComShaovieCex(in *jlexer.Lexer, out *GateWsSpotPubMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "channel":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Channel = string(in.String())
			}
		case "event":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Event = string(in.String())
			}
		case "result":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Data).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC89930e1EncodeGithubComShaovieCex(out *jwriter.Writer, in GateWsSpotPubMsg) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Channel != "" {
		const prefix string = ",\"channel\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Channel))
	}
	if in.Event != "" {
		const prefix string = ",\"event\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Event))
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"result\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Data).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GateWsSpotPubMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC89930e1EncodeGithubComShaovieCex(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GateWsSpotPubMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC89930e1EncodeGithubComShaovieCex(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GateWsSpotPubMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC89930e1DecodeGithubComShaovieCex(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GateWsSpotPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC89930e1DecodeGithubComShaovieCex(l, v)
}
func easyjsonC89930e1DecodeGithubComShaovieCex1(in *jlexer.Lexer, out *GateWsContractPubMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "channel":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Channel = string(in.String())
			}
		case "event":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Event = string(in.String())
			}
		case "result":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Data).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC89930e1EncodeGithubComShaovieCex1(out *jwriter.Writer, in GateWsContractPubMsg) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Channel != "" {
		const prefix string = ",\"channel\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Channel))
	}
	if in.Event != "" {
		const prefix string = ",\"event\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Event))
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"result\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Data).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GateWsContractPubMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC89930e1EncodeGithubComShaovieCex1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GateWsContractPubMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC89930e1EncodeGithubComShaovieCex1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GateWsContractPubMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC89930e1DecodeGithubComShaovieCex1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GateWsContractPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC89930e1DecodeGithubComShaovieCex1(l, v)
}
func easyjsonC89930e1DecodeGithubComShaovieCex2(in *jlexer.Lexer, out *GateSpotOrderBook) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "t":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "bids":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Bids = [][2]decimal.Decimal{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v1 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v2 := 0
						for !in.IsDelim(']') {
							if v2 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v1)[v2]).UnmarshalJSON(data))
									}
								}
								v2++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Bids = append(out.Bids, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "asks":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Asks = [][2]decimal.Decimal{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v3 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v4 := 0
						for !in.IsDelim(']') {
							if v4 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v3)[v4]).UnmarshalJSON(data))
									}
								}
								v4++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Asks = append(out.Asks, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC89930e1EncodeGithubComShaovieCex2(out *jwriter.Writer, in GateSpotOrderBook) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Symbol != "" {
		const prefix string = ",\"s\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	if in.Time != 0 {
		const prefix string = ",\"t\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Time))
	}
	if len(in.Bids) != 0 {
		const prefix string = ",\"bids\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v5, v6 := range in.Bids {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v7 := range v6 {
					if v7 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v6)[v7]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	if len(in.Asks) != 0 {
		const prefix string = ",\"asks\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v8, v9 := range in.Asks {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v10 := range v9 {
					if v10 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v9)[v10]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GateSpotOrderBook) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC89930e1EncodeGithubComShaovieCex2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GateSpotOrderBook) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC89930e1EncodeGithubComShaovieCex2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GateSpotOrderBook) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC89930e1DecodeGithubComShaovieCex2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GateSpotOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC89930e1DecodeGithubComShaovieCex2(l, v)
}
func easyjsonC89930e1DecodeGithubComShaovieCex3(in *jlexer.Lexer, out *GateSpot24hTicker) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "currency_pair":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "last":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Last).UnmarshalJSON(data))
				}
			}
		case "base_volume":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Volume).UnmarshalJSON(data))
				}
			}
		case "quote_volume":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.QuoteVolume).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC89930e1EncodeGithubComShaovieCex3(out *jwriter.Writer, in GateSpot24hTicker) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"currency_pair\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"last\":"
		out.RawString(prefix)
		out.Raw((in.Last).MarshalJSON())
	}
	{
		const prefix string = ",\"base_volume\":"
		out.RawString(prefix)
		out.Raw((in.Volume).MarshalJSON())
	}
	{
		const prefix string = ",\"quote_volume\":"
		out.RawString(prefix)
		out.Raw((in.QuoteVolume).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GateSpot24hTicker) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC89930e1EncodeGithubComShaovieCex3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GateSpot24hTicker) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC89930e1EncodeGithubComShaovieCex3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GateSpot24hTicker) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC89930e1DecodeGithubComShaovieCex3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GateSpot24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC89930e1DecodeGithubComShaovieCex3(l, v)
}
func easyjsonC89930e1DecodeGithubComShaovieCex4(in *jlexer.Lexer, out *GateFundingRate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "funding_next_apply":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NextTime = int64(in.Int64())
			}
		case "funding_rate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Fr).UnmarshalJSON(data))
				}
			}
		case "in_delisting":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offline = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC89930e1EncodeGithubComShaovieCex4(out *jwriter.Writer, in GateFundingRate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.NextTime != 0 {
		const prefix string = ",\"funding_next_apply\":"
		out.RawString(prefix)
		out.Int64(int64(in.NextTime))
	}
	if true {
		const prefix string = ",\"funding_rate\":"
		out.RawString(prefix)
		out.Raw((in.Fr).MarshalJSON())
	}
	if in.Offline {
		const prefix string = ",\"in_delisting\":"
		out.RawString(prefix)
		out.Bool(bool(in.Offline))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GateFundingRate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC89930e1EncodeGithubComShaovieCex4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GateFundingRate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC89930e1EncodeGithubComShaovieCex4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GateFundingRate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC89930e1DecodeGithubComShaovieCex4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GateFundingRate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC89930e1DecodeGithubComShaovieCex4(l, v)
}
func easyjsonC89930e1DecodeGithubComShaovieCex5(in *jlexer.Lexer, out *GateContractOrderBookTick) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "p":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Price).UnmarshalJSON(data))
				}
			}
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Size).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC89930e1EncodeGithubComShaovieCex5(out *jwriter.Writer, in GateContractOrderBookTick) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"p\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((in.Price).MarshalJSON())
	}
	if true {
		const prefix string = ",\"s\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Size).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GateContractOrderBookTick) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC89930e1EncodeGithubComShaovieCex5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GateContractOrderBookTick) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC89930e1EncodeGithubComShaovieCex5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GateContractOrderBookTick) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC89930e1DecodeGithubComShaovieCex5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GateContractOrderBookTick) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC89930e1DecodeGithubComShaovieCex5(l, v)
}
func easyjsonC89930e1DecodeGithubComShaovieCex6(in *jlexer.Lexer, out *GateContractOrderBook) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contract":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "t":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "bids":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([]GateContractOrderBookTick, 0, 2)
					} else {
						out.Bids = []GateContractOrderBookTick{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v11 GateContractOrderBookTick
					if in.IsNull() {
						in.Skip()
					} else {
						(v11).UnmarshalEasyJSON(in)
					}
					out.Bids = append(out.Bids, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "asks":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([]GateContractOrderBookTick, 0, 2)
					} else {
						out.Asks = []GateContractOrderBookTick{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v12 GateContractOrderBookTick
					if in.IsNull() {
						in.Skip()
					} else {
						(v12).UnmarshalEasyJSON(in)
					}
					out.Asks = append(out.Asks, v12)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC89930e1EncodeGithubComShaovieCex6(out *jwriter.Writer, in GateContractOrderBook) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Symbol != "" {
		const prefix string = ",\"contract\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	if in.Time != 0 {
		const prefix string = ",\"t\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Time))
	}
	if len(in.Bids) != 0 {
		const prefix string = ",\"bids\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v13, v14 := range in.Bids {
				if v13 > 0 {
					out.RawByte(',')
				}
				(v14).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Asks) != 0 {
		const prefix string = ",\"asks\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v15, v16 := range in.Asks {
				if v15 > 0 {
					out.RawByte(',')
				}
				(v16).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GateContractOrderBook) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC89930e1EncodeGithubComShaovieCex6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GateContractOrderBook) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC89930e1EncodeGithubComShaovieCex6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GateContractOrderBook) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC89930e1DecodeGithubComShaovieCex6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GateContractOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC89930e1DecodeGithubComShaovieCex6(l, v)
}
func easyjsonC89930e1DecodeGithubComShaovieCex7(in *jlexer.Lexer, out *GateContract24hTicker) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contract":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "last":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Last).UnmarshalJSON(data))
				}
			}
		case "volume_24h_base":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Volume).UnmarshalJSON(data))
				}
			}
		case "volume_24h_quote":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.QuoteVolume).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC89930e1EncodeGithubComShaovieCex7(out *jwriter.Writer, in GateContract24hTicker) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contract\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"last\":"
		out.RawString(prefix)
		out.Raw((in.Last).MarshalJSON())
	}
	{
		const prefix string = ",\"volume_24h_base\":"
		out.RawString(prefix)
		out.Raw((in.Volume).MarshalJSON())
	}
	{
		const prefix string = ",\"volume_24h_quote\":"
		out.RawString(prefix)
		out.Raw((in.QuoteVolume).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GateContract24hTicker) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC89930e1EncodeGithubComShaovieCex7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GateContract24hTicker) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC89930e1EncodeGithubComShaovieCex7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GateContract24hTicker) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC89930e1DecodeGithubComShaovieCex7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GateContract24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC89930e1DecodeGithubComShaovieCex7(l, v)
}
