// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package cex

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (GateContract24hTicker) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*GateContract24hTicker) UnmarshalJSON([]byte) error        { return nil }
func (GateContract24hTicker) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*GateContract24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GateContract24hTicker *GateContract24hTicker

func (GateContractOrderBook) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*GateContractOrderBook) UnmarshalJSON([]byte) error        { return nil }
func (GateContractOrderBook) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*GateContractOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GateContractOrderBook *GateContractOrderBook

func (GateContractOrderBookTick) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*GateContractOrderBookTick) UnmarshalJSON([]byte) error        { return nil }
func (GateContractOrderBookTick) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*GateContractOrderBookTick) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GateContractOrderBookTick *GateContractOrderBookTick

func (GateFundingRate) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*GateFundingRate) UnmarshalJSON([]byte) error        { return nil }
func (GateFundingRate) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*GateFundingRate) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GateFundingRate *GateFundingRate

func (GateSpot24hTicker) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*GateSpot24hTicker) UnmarshalJSON([]byte) error        { return nil }
func (GateSpot24hTicker) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*GateSpot24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GateSpot24hTicker *GateSpot24hTicker

func (GateSpotOrderBook) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*GateSpotOrderBook) UnmarshalJSON([]byte) error        { return nil }
func (GateSpotOrderBook) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*GateSpotOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GateSpotOrderBook *GateSpotOrderBook

func (GateWsContractPubMsg) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*GateWsContractPubMsg) UnmarshalJSON([]byte) error        { return nil }
func (GateWsContractPubMsg) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*GateWsContractPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GateWsContractPubMsg *GateWsContractPubMsg

func (GateWsSpotPubMsg) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*GateWsSpotPubMsg) UnmarshalJSON([]byte) error        { return nil }
func (GateWsSpotPubMsg) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*GateWsSpotPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GateWsSpotPubMsg *GateWsSpotPubMsg
