// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cex

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF72c1e69DecodeGithubComShaovieCex(in *jlexer.Lexer, out *KtxWsPubMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "pong":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Pong = float64(in.Float64())
			}
		case "op":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Op = string(in.String())
			}
		case "stream":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Stream = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Data).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF72c1e69EncodeGithubComShaovieCex(out *jwriter.Writer, in KtxWsPubMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"pong\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Pong))
	}
	{
		const prefix string = ",\"op\":"
		out.RawString(prefix)
		out.String(string(in.Op))
	}
	{
		const prefix string = ",\"stream\":"
		out.RawString(prefix)
		out.String(string(in.Stream))
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.Raw((in.Data).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v KtxWsPubMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF72c1e69EncodeGithubComShaovieCex(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v KtxWsPubMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF72c1e69EncodeGithubComShaovieCex(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *KtxWsPubMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF72c1e69DecodeGithubComShaovieCex(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *KtxWsPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF72c1e69DecodeGithubComShaovieCex(l, v)
}
func easyjsonF72c1e69DecodeGithubComShaovieCex1(in *jlexer.Lexer, out *KtxTicker) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "product":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "bidPrice":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BidPrice).UnmarshalJSON(data))
				}
			}
		case "bidQty":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BidQty).UnmarshalJSON(data))
				}
			}
		case "askPrice":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.AskPrice).UnmarshalJSON(data))
				}
			}
		case "askQty":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.AskQty).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF72c1e69EncodeGithubComShaovieCex1(out *jwriter.Writer, in KtxTicker) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"product\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"bidPrice\":"
		out.RawString(prefix)
		out.Raw((in.BidPrice).MarshalJSON())
	}
	{
		const prefix string = ",\"bidQty\":"
		out.RawString(prefix)
		out.Raw((in.BidQty).MarshalJSON())
	}
	{
		const prefix string = ",\"askPrice\":"
		out.RawString(prefix)
		out.Raw((in.AskPrice).MarshalJSON())
	}
	{
		const prefix string = ",\"askQty\":"
		out.RawString(prefix)
		out.Raw((in.AskQty).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v KtxTicker) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF72c1e69EncodeGithubComShaovieCex1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v KtxTicker) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF72c1e69EncodeGithubComShaovieCex1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *KtxTicker) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF72c1e69DecodeGithubComShaovieCex1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *KtxTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF72c1e69DecodeGithubComShaovieCex1(l, v)
}
