// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cex

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	decimal "github.com/shopspring/decimal"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBb14c8deDecodeGithubComShaovieCex(in *jlexer.Lexer, out *OkxWsPubMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "arg":
			easyjsonBb14c8deDecode(in, &out.Arg)
		case "event":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Event = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Data).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBb14c8deEncodeGithubComShaovieCex(out *jwriter.Writer, in OkxWsPubMsg) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"arg\":"
		first = false
		out.RawString(prefix[1:])
		easyjsonBb14c8deEncode(out, in.Arg)
	}
	if in.Event != "" {
		const prefix string = ",\"event\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Event))
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.Data).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OkxWsPubMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBb14c8deEncodeGithubComShaovieCex(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OkxWsPubMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBb14c8deEncodeGithubComShaovieCex(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OkxWsPubMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBb14c8deDecodeGithubComShaovieCex(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OkxWsPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBb14c8deDecodeGithubComShaovieCex(l, v)
}
func easyjsonBb14c8deDecode(in *jlexer.Lexer, out *struct {
	Channel string `json:"channel,omitempty"`
	Symbol  string `json:"instId,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "channel":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Channel = string(in.String())
			}
		case "instId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBb14c8deEncode(out *jwriter.Writer, in struct {
	Channel string `json:"channel,omitempty"`
	Symbol  string `json:"instId,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Channel != "" {
		const prefix string = ",\"channel\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Channel))
	}
	if in.Symbol != "" {
		const prefix string = ",\"instId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Symbol))
	}
	out.RawByte('}')
}
func easyjsonBb14c8deDecodeGithubComShaovieCex1(in *jlexer.Lexer, out *OkxOrderBooks) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]OkxOrderBook, 0, 1)
					} else {
						out.Data = []OkxOrderBook{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v1 OkxOrderBook
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Data = append(out.Data, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBb14c8deEncodeGithubComShaovieCex1(out *jwriter.Writer, in OkxOrderBooks) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.Data {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OkxOrderBooks) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBb14c8deEncodeGithubComShaovieCex1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OkxOrderBooks) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBb14c8deEncodeGithubComShaovieCex1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OkxOrderBooks) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBb14c8deDecodeGithubComShaovieCex1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OkxOrderBooks) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBb14c8deDecodeGithubComShaovieCex1(l, v)
}
func easyjsonBb14c8deDecodeGithubComShaovieCex2(in *jlexer.Lexer, out *OkxOrderBook) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ts":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = string(in.String())
			}
		case "bids":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Bids = [][2]decimal.Decimal{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v4 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v5 := 0
						for !in.IsDelim(']') {
							if v5 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v4)[v5]).UnmarshalJSON(data))
									}
								}
								v5++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Bids = append(out.Bids, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "asks":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([][2]decimal.Decimal, 0, 2)
					} else {
						out.Asks = [][2]decimal.Decimal{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v6 [2]decimal.Decimal
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v7 := 0
						for !in.IsDelim(']') {
							if v7 < 2 {
								if in.IsNull() {
									in.Skip()
								} else {
									if data := in.Raw(); in.Ok() {
										in.AddError(((v6)[v7]).UnmarshalJSON(data))
									}
								}
								v7++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Asks = append(out.Asks, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBb14c8deEncodeGithubComShaovieCex2(out *jwriter.Writer, in OkxOrderBook) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Time != "" {
		const prefix string = ",\"ts\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Time))
	}
	if len(in.Bids) != 0 {
		const prefix string = ",\"bids\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v8, v9 := range in.Bids {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v10 := range v9 {
					if v10 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v9)[v10]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	if len(in.Asks) != 0 {
		const prefix string = ",\"asks\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v11, v12 := range in.Asks {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v13 := range v12 {
					if v13 > 0 {
						out.RawByte(',')
					}
					out.Raw(((v12)[v13]).MarshalJSON())
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OkxOrderBook) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBb14c8deEncodeGithubComShaovieCex2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OkxOrderBook) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBb14c8deEncodeGithubComShaovieCex2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OkxOrderBook) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBb14c8deDecodeGithubComShaovieCex2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OkxOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBb14c8deDecodeGithubComShaovieCex2(l, v)
}
func easyjsonBb14c8deDecodeGithubComShaovieCex3(in *jlexer.Lexer, out *OkxKLine) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "msg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Msg = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([][9]string, 0, 0)
					} else {
						out.Data = [][9]string{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v14 [9]string
					if in.IsNull() {
						in.Skip()
					} else {
						in.Delim('[')
						v15 := 0
						for !in.IsDelim(']') {
							if v15 < 9 {
								if in.IsNull() {
									in.Skip()
								} else {
									(v14)[v15] = string(in.String())
								}
								v15++
							} else {
								in.SkipRecursive()
							}
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Data = append(out.Data, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBb14c8deEncodeGithubComShaovieCex3(out *jwriter.Writer, in OkxKLine) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Code != "" {
		const prefix string = ",\"code\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	if in.Msg != "" {
		const prefix string = ",\"msg\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Msg))
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v16, v17 := range in.Data {
				if v16 > 0 {
					out.RawByte(',')
				}
				out.RawByte('[')
				for v18 := range v17 {
					if v18 > 0 {
						out.RawByte(',')
					}
					out.String(string((v17)[v18]))
				}
				out.RawByte(']')
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OkxKLine) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBb14c8deEncodeGithubComShaovieCex3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OkxKLine) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBb14c8deEncodeGithubComShaovieCex3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OkxKLine) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBb14c8deDecodeGithubComShaovieCex3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OkxKLine) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBb14c8deDecodeGithubComShaovieCex3(l, v)
}
func easyjsonBb14c8deDecodeGithubComShaovieCex4(in *jlexer.Lexer, out *OkxFundingRates) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "msg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Msg = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]struct {
							Symbol   string          `json:"instId"`
							InstType string          `json:"instType"`
							NextTime string          `json:"nextFundingTime,omitempty"`
							Fr       decimal.Decimal `json:"fundingRate,omitempty"`
						}, 0, 1)
					} else {
						out.Data = []struct {
							Symbol   string          `json:"instId"`
							InstType string          `json:"instType"`
							NextTime string          `json:"nextFundingTime,omitempty"`
							Fr       decimal.Decimal `json:"fundingRate,omitempty"`
						}{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v19 struct {
						Symbol   string          `json:"instId"`
						InstType string          `json:"instType"`
						NextTime string          `json:"nextFundingTime,omitempty"`
						Fr       decimal.Decimal `json:"fundingRate,omitempty"`
					}
					easyjsonBb14c8deDecode1(in, &v19)
					out.Data = append(out.Data, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBb14c8deEncodeGithubComShaovieCex4(out *jwriter.Writer, in OkxFundingRates) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Code != "" {
		const prefix string = ",\"code\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	if in.Msg != "" {
		const prefix string = ",\"msg\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Msg))
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v20, v21 := range in.Data {
				if v20 > 0 {
					out.RawByte(',')
				}
				easyjsonBb14c8deEncode1(out, v21)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OkxFundingRates) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBb14c8deEncodeGithubComShaovieCex4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OkxFundingRates) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBb14c8deEncodeGithubComShaovieCex4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OkxFundingRates) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBb14c8deDecodeGithubComShaovieCex4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OkxFundingRates) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBb14c8deDecodeGithubComShaovieCex4(l, v)
}
func easyjsonBb14c8deDecode1(in *jlexer.Lexer, out *struct {
	Symbol   string          `json:"instId"`
	InstType string          `json:"instType"`
	NextTime string          `json:"nextFundingTime,omitempty"`
	Fr       decimal.Decimal `json:"fundingRate,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "instId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "instType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InstType = string(in.String())
			}
		case "nextFundingTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NextTime = string(in.String())
			}
		case "fundingRate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Fr).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBb14c8deEncode1(out *jwriter.Writer, in struct {
	Symbol   string          `json:"instId"`
	InstType string          `json:"instType"`
	NextTime string          `json:"nextFundingTime,omitempty"`
	Fr       decimal.Decimal `json:"fundingRate,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"instId\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"instType\":"
		out.RawString(prefix)
		out.String(string(in.InstType))
	}
	if in.NextTime != "" {
		const prefix string = ",\"nextFundingTime\":"
		out.RawString(prefix)
		out.String(string(in.NextTime))
	}
	if true {
		const prefix string = ",\"fundingRate\":"
		out.RawString(prefix)
		out.Raw((in.Fr).MarshalJSON())
	}
	out.RawByte('}')
}
func easyjsonBb14c8deDecodeGithubComShaovieCex5(in *jlexer.Lexer, out *Okx24hTickers) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "msg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Msg = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]Okx24hTicker, 0, 1)
					} else {
						out.Data = []Okx24hTicker{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v22 Okx24hTicker
					if in.IsNull() {
						in.Skip()
					} else {
						(v22).UnmarshalEasyJSON(in)
					}
					out.Data = append(out.Data, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBb14c8deEncodeGithubComShaovieCex5(out *jwriter.Writer, in Okx24hTickers) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Code != "" {
		const prefix string = ",\"code\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	if in.Msg != "" {
		const prefix string = ",\"msg\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Msg))
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v23, v24 := range in.Data {
				if v23 > 0 {
					out.RawByte(',')
				}
				(v24).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Okx24hTickers) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBb14c8deEncodeGithubComShaovieCex5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Okx24hTickers) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBb14c8deEncodeGithubComShaovieCex5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Okx24hTickers) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBb14c8deDecodeGithubComShaovieCex5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Okx24hTickers) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBb14c8deDecodeGithubComShaovieCex5(l, v)
}
func easyjsonBb14c8deDecodeGithubComShaovieCex6(in *jlexer.Lexer, out *Okx24hTicker) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "instId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "last":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Last).UnmarshalJSON(data))
				}
			}
		case "vol24h":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Volume).UnmarshalJSON(data))
				}
			}
		case "volCcy24h":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.QuoteVolume).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBb14c8deEncodeGithubComShaovieCex6(out *jwriter.Writer, in Okx24hTicker) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"instId\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"last\":"
		out.RawString(prefix)
		out.Raw((in.Last).MarshalJSON())
	}
	{
		const prefix string = ",\"vol24h\":"
		out.RawString(prefix)
		out.Raw((in.Volume).MarshalJSON())
	}
	{
		const prefix string = ",\"volCcy24h\":"
		out.RawString(prefix)
		out.Raw((in.QuoteVolume).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Okx24hTicker) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBb14c8deEncodeGithubComShaovieCex6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Okx24hTicker) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBb14c8deEncodeGithubComShaovieCex6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Okx24hTicker) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBb14c8deDecodeGithubComShaovieCex6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Okx24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBb14c8deDecodeGithubComShaovieCex6(l, v)
}
