// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package cex

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (Okx24hTicker) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Okx24hTicker) UnmarshalJSON([]byte) error        { return nil }
func (Okx24hTicker) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Okx24hTicker) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Okx24hTicker *Okx24hTicker

func (Okx24hTickers) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Okx24hTickers) UnmarshalJSON([]byte) error        { return nil }
func (Okx24hTickers) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Okx24hTickers) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Okx24hTickers *Okx24hTickers

func (OkxFundingRates) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OkxFundingRates) UnmarshalJSON([]byte) error        { return nil }
func (OkxFundingRates) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OkxFundingRates) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OkxFundingRates *OkxFundingRates

func (OkxKLine) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OkxKLine) UnmarshalJSON([]byte) error        { return nil }
func (OkxKLine) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OkxKLine) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OkxKLine *OkxKLine

func (OkxOrderBook) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OkxOrderBook) UnmarshalJSON([]byte) error        { return nil }
func (OkxOrderBook) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OkxOrderBook) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OkxOrderBook *OkxOrderBook

func (OkxOrderBooks) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OkxOrderBooks) UnmarshalJSON([]byte) error        { return nil }
func (OkxOrderBooks) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OkxOrderBooks) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OkxOrderBooks *OkxOrderBooks

func (OkxWsPubMsg) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OkxWsPubMsg) UnmarshalJSON([]byte) error        { return nil }
func (OkxWsPubMsg) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OkxWsPubMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OkxWsPubMsg *OkxWsPubMsg
